# Generated by Django 4.2.5 on 2023-09-18 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
