# Generated by Django 4.2.5 on 2023-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_category_remove_record_type_record_is_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#A0A0A0', max_length=7),
        ),
    ]
